// *********************************************************************
// **
// ** Copyright (C) 2017 Antonio David López Machado
// **
// ** This program is free software: you can redistribute it and/or modify
// ** it under the terms of the GNU General Public License as published by
// ** the Free Software Foundation, either version 3 of the License, or
// ** (at your option) any later version.
// **
// ** This program is distributed in the hope that it will be useful,
// ** but WITHOUT ANY WARRANTY; without even the implied warranty of
// ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// ** GNU General Public License for more details.
// **
// ** You should have received a copy of the GNU General Public License
// ** along with this program.  If not, see <http://www.gnu.org/licenses/>.
// **
// *********************************************************************
package GUI;

/**
 * Clase que nos permite mostrar la información de la aplicación(autor, versión, etc) 
 * @author Antonio David López Machado antoniolm@correo.ugr.es
 */
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("About");
        setLocation(100, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SouthPanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        NorthPanel = new javax.swing.JPanel();
        CenterPanel = new javax.swing.JPanel();
        NameProgramField = new javax.swing.JLabel();
        VersionField = new javax.swing.JLabel();
        AuthorField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SouthPanel.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout SouthPanelLayout = new javax.swing.GroupLayout(SouthPanel);
        SouthPanel.setLayout(SouthPanelLayout);
        SouthPanelLayout.setHorizontalGroup(
            SouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        SouthPanelLayout.setVerticalGroup(
            SouthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(SouthPanel, java.awt.BorderLayout.PAGE_END);

        LeftPanel.setPreferredSize(new java.awt.Dimension(20, 150));

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(LeftPanel, java.awt.BorderLayout.LINE_END);

        RightPanel.setPreferredSize(new java.awt.Dimension(20, 150));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        getContentPane().add(RightPanel, java.awt.BorderLayout.LINE_START);

        NorthPanel.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout NorthPanelLayout = new javax.swing.GroupLayout(NorthPanel);
        NorthPanel.setLayout(NorthPanelLayout);
        NorthPanelLayout.setHorizontalGroup(
            NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );
        NorthPanelLayout.setVerticalGroup(
            NorthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(NorthPanel, java.awt.BorderLayout.PAGE_START);

        CenterPanel.setMinimumSize(new java.awt.Dimension(120, 48));
        CenterPanel.setLayout(new java.awt.GridLayout(3, 3));

        NameProgramField.setText("DrawEditor");
        CenterPanel.add(NameProgramField);

        VersionField.setText("version : 1.05");
        CenterPanel.add(VersionField);

        AuthorField.setText("Author: Antonio David López Machado");
        CenterPanel.add(AuthorField);

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorField;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JLabel NameProgramField;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JLabel VersionField;
    // End of variables declaration//GEN-END:variables
}
