// *********************************************************************
// **
// ** Copyright (C) 2017 Antonio David López Machado
// **
// ** This program is free software: you can redistribute it and/or modify
// ** it under the terms of the GNU General Public License as published by
// ** the Free Software Foundation, either version 3 of the License, or
// ** (at your option) any later version.
// **
// ** This program is distributed in the hope that it will be useful,
// ** but WITHOUT ANY WARRANTY; without even the implied warranty of
// ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// ** GNU General Public License for more details.
// **
// ** You should have received a copy of the GNU General Public License
// ** along with this program.  If not, see <http://www.gnu.org/licenses/>.
// **
// *********************************************************************


package GUI;

import static GUI.GeometryType.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

enum GeometryType{
    POINT,
    LINE,
    RECTANGLE,
    CIRCLE
}


public class CanvasPanel extends javax.swing.JPanel {
    GeometryType type;
    Point initialPos,currentPos;
    boolean isClicked,filled;
    Color currentColor;
    
    public CanvasPanel() {
        initComponents();
        
        type=POINT;
        currentColor=Color.BLACK;
        isClicked=false;
        filled=false;
        initialPos=new Point();
        currentPos=new Point();
        setBackground(Color.white);
        
        addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e){
                    initialPos=e.getPoint();
                    isClicked=true;
                    repaint();                    
                }
        });
        
        addMouseMotionListener(new MouseAdapter() {
                @Override
                public void mouseDragged(MouseEvent e){
                    currentPos=e.getPoint();
                    repaint();                    
                }
        });
    }
    
    public void paint(Graphics g){
        super.paint(g);
        g.setColor(currentColor);
        if(isClicked){
            switch(type){
                case POINT:
                    g.fillOval(initialPos.x, initialPos.y, 10, 10);
                break;
                case LINE:
                    g.drawLine(initialPos.x, initialPos.y, currentPos.x, currentPos.y);
                break;
                case RECTANGLE:
                    if(!filled)
                        g.drawRect(Math.min(currentPos.x, initialPos.x), Math.min(currentPos.y, initialPos.y),
                                Math.abs(initialPos.x - currentPos.x), Math.abs(initialPos.y - currentPos.y));
                    else
                        g.fillRect(Math.min(currentPos.x, initialPos.x), Math.min(currentPos.y, initialPos.y),
                                Math.abs(initialPos.x - currentPos.x), Math.abs(initialPos.y - currentPos.y));
                break;
                case CIRCLE:
                    if(!filled)
                        g.drawOval(Math.min(currentPos.x, initialPos.x), Math.min(currentPos.y, initialPos.y),
                                Math.abs(initialPos.x - currentPos.x), Math.abs(initialPos.y - currentPos.y));
                    else
                        g.fillOval(Math.min(currentPos.x, initialPos.x), Math.min(currentPos.y, initialPos.y),
                                Math.abs(initialPos.x - currentPos.x), Math.abs(initialPos.y - currentPos.y));
                break;

            }
        }
    }
    
    public void setType(GeometryType aType){
        type=aType;
    }
    
    public void setFilled(boolean value){
        filled=value;
    }
    
    public void setColor(Color value){
        currentColor=value;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
